In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/ieee-fraud-detection/sample_submission.csv
/kaggle/input/competitions/ieee-fraud-detection/test_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/train_identity.csv
/kaggle/input/competitions/ieee-fraud-detection/test_transaction.csv
/kaggle/input/competitions/ieee-fraud-detection/train_transaction.csv

In [2]:
train_transaction = pd.read_csv('/kaggle/input/competitions/ieee-fraud-detection/train_transaction.csv')
train_identity = pd.read_csv('/kaggle/input/competitions/ieee-fraud-detection/train_identity.csv')
test_transaction = pd.read_csv('/kaggle/input/competitions/ieee-fraud-detection/test_transaction.csv')
test_identity = pd.read_csv('/kaggle/input/competitions/ieee-fraud-detection/test_identity.csv')

In [3]:
train_df = train_identity.merge(train_transaction)

In [4]:
train_transaction.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
train_transaction.shape

(590540, 394)

In [6]:
train_transaction.isna().sum()

TransactionID          0
isFraud                0
TransactionDT          0
TransactionAmt         0
ProductCD              0
                   ...
V335              508189
V336              508189
V337              508189
V338              508189
V339              508189
Length: 394, dtype: int64

In [7]:
for i in train_transaction.columns:
    no = train_transaction[i].isna().sum()
    if no > 50000:
        print(i,':',no.sum())
print(f'Highest missing val ;{i}')

addr1 : 65706
addr2 : 65706
dist1 : 352271
dist2 : 552913
P_emaildomain : 94456
R_emaildomain : 453249
D2 : 280797
D3 : 262878
D4 : 168922
D5 : 309841
D6 : 517353
D7 : 551623
D8 : 515614
D9 : 515614
D10 : 76022
D11 : 279287
D12 : 525823
D13 : 528588
D14 : 528353
D15 : 89113
M1 : 271100
M2 : 271100
M3 : 271100
M4 : 281444
M5 : 350482
M6 : 169360
M7 : 346265
M8 : 346252
M9 : 346252
V1 : 279287
V2 : 279287
V3 : 279287
V4 : 279287
V5 : 279287
V6 : 279287
V7 : 279287
V8 : 279287
V9 : 279287
V10 : 279287
V11 : 279287
V12 : 76073
V13 : 76073
V14 : 76073
V15 : 76073
V16 : 76073
V17 : 76073
V18 : 76073
V19 : 76073
V20 : 76073
V21 : 76073
V22 : 76073
V23 : 76073
V24 : 76073
V25 : 76073
V26 : 76073
V27 : 76073
V28 : 76073
V29 : 76073
V30 : 76073
V31 : 76073
V32 : 76073
V33 : 76073
V34 : 76073
V35 : 168969
V36 : 168969
V37 : 168969
V38 : 168969
V39 : 168969
V40 : 168969
V41 : 168969
V42 : 168969
V43 : 168969
V44 : 168969
V45 : 168969
V46 : 168969
V47 : 168969
V48 : 168969
V49 : 168969
V50 : 168969
V51 : 168969
V52 : 168969
V53 : 77096
V54 : 77096
V55 : 77096
V56 : 77096
V57 : 77096
V58 : 77096
V59 : 77096
V60 : 77096
V61 : 77096
V62 : 77096
V63 : 77096
V64 : 77096
V65 : 77096
V66 : 77096
V67 : 77096
V68 : 77096
V69 : 77096
V70 : 77096
V71 : 77096
V72 : 77096
V73 : 77096
V74 : 77096
V75 : 89164
V76 : 89164
V77 : 89164
V78 : 89164
V79 : 89164
V80 : 89164
V81 : 89164
V82 : 89164
V83 : 89164
V84 : 89164
V85 : 89164
V86 : 89164
V87 : 89164
V88 : 89164
V89 : 89164
V90 : 89164
V91 : 89164
V92 : 89164
V93 : 89164
V94 : 89164
V138 : 508595
V139 : 508595
V140 : 508595
V141 : 508595
V142 : 508595
V143 : 508589
V144 : 508589
V145 : 508589
V146 : 508595
V147 : 508595
V148 : 508595
V149 : 508595
V150 : 508589
V151 : 508589
V152 : 508589
V153 : 508595
V154 : 508595
V155 : 508595
V156 : 508595
V157 : 508595
V158 : 508595
V159 : 508589
V160 : 508589
V161 : 508595
V162 : 508595
V163 : 508595
V164 : 508589
V165 : 508589
V166 : 508589
V167 : 450909
V168 : 450909
V169 : 450721
V170 : 450721
V171 : 450721
V172 : 450909
V173 : 450909
V174 : 450721
V175 : 450721
V176 : 450909
V177 : 450909
V178 : 450909
V179 : 450909
V180 : 450721
V181 : 450909
V182 : 450909
V183 : 450909
V184 : 450721
V185 : 450721
V186 : 450909
V187 : 450909
V188 : 450721
V189 : 450721
V190 : 450909
V191 : 450909
V192 : 450909
V193 : 450909
V194 : 450721
V195 : 450721
V196 : 450909
V197 : 450721
V198 : 450721
V199 : 450909
V200 : 450721
V201 : 450721
V202 : 450909
V203 : 450909
V204 : 450909
V205 : 450909
V206 : 450909
V207 : 450909
V208 : 450721
V209 : 450721
V210 : 450721
V211 : 450909
V212 : 450909
V213 : 450909
V214 : 450909
V215 : 450909
V216 : 450909
V217 : 460110
V218 : 460110
V219 : 460110
V220 : 449124
V221 : 449124
V222 : 449124
V223 : 460110
V224 : 460110
V225 : 460110
V226 : 460110
V227 : 449124
V228 : 460110
V229 : 460110
V230 : 460110
V231 : 460110
V232 : 460110
V233 : 460110
V234 : 449124
V235 : 460110
V236 : 460110
V237 : 460110
V238 : 449124
V239 : 449124
V240 : 460110
V241 : 460110
V242 : 460110
V243 : 460110
V244 : 460110
V245 : 449124
V246 : 460110
V247 : 460110
V248 : 460110
V249 : 460110
V250 : 449124
V251 : 449124
V252 : 460110
V253 : 460110
V254 : 460110
V255 : 449124
V256 : 449124
V257 : 460110
V258 : 460110
V259 : 449124
V260 : 460110
V261 : 460110
V262 : 460110
V263 : 460110
V264 : 460110
V265 : 460110
V266 : 460110
V267 : 460110
V268 : 460110
V269 : 460110
V270 : 449124
V271 : 449124
V272 : 449124
V273 : 460110
V274 : 460110
V275 : 460110
V276 : 460110
V277 : 460110
V278 : 460110
V322 : 508189
V323 : 508189
V324 : 508189
V325 : 508189
V326 : 508189
V327 : 508189
V328 : 508189
V329 : 508189
V330 : 508189
V331 : 508189
V332 : 508189
V333 : 508189
V334 : 508189
V335 : 508189
V336 : 508189
V337 : 508189
V338 : 508189
V339 : 508189
Highest missing val ;V339

In [8]:
small_df = train_transaction.dropna(subset=['V339'])

In [9]:
small_df.head()

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2987008,0,86535,15.0,H,2803,100.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2987016,0,86620,30.0,H,1790,555.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2987017,0,86668,100.0,H,11492,111.0,150.0,mastercard,219.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2987022,0,86786,50.0,H,1724,583.0,150.0,visa,226.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
small_df.shape

(82351, 394)

In [11]:
small_df.isna().sum()

TransactionID     0
isFraud           0
TransactionDT     0
TransactionAmt    0
ProductCD         0
                 ..
V335              0
V336              0
V337              0
V338              0
V339              0
Length: 394, dtype: int64

In [12]:
for col in small_df.columns:
    num = small_df[col].isna().sum()
    if num > 0:
        print(col,':',num.sum())

card2 : 397
card3 : 1
card4 : 11
card5 : 583
card6 : 7
addr1 : 343
addr2 : 343
dist1 : 82351
dist2 : 71465
P_emaildomain : 11674
R_emaildomain : 11426
D1 : 41
D2 : 69728
D3 : 77844
D4 : 76131
D5 : 79085
D6 : 73516
D7 : 75937
D8 : 36861
D9 : 36861
D10 : 72272
D11 : 82351
D12 : 82351
D13 : 78347
D14 : 71247
D15 : 72785
M1 : 82351
M2 : 82351
M3 : 82351
M4 : 82351
M5 : 82351
M6 : 82351
M7 : 82351
M8 : 82351
M9 : 82351
V1 : 82351
V2 : 82351
V3 : 82351
V4 : 82351
V5 : 82351
V6 : 82351
V7 : 82351
V8 : 82351
V9 : 82351
V10 : 82351
V11 : 82351
V12 : 72323
V13 : 72323
V14 : 72323
V15 : 72323
V16 : 72323
V17 : 72323
V18 : 72323
V19 : 72323
V20 : 72323
V21 : 72323
V22 : 72323
V23 : 72323
V24 : 72323
V25 : 72323
V26 : 72323
V27 : 72323
V28 : 72323
V29 : 72323
V30 : 72323
V31 : 72323
V32 : 72323
V33 : 72323
V34 : 72323
V35 : 76154
V36 : 76154
V37 : 76154
V38 : 76154
V39 : 76154
V40 : 76154
V41 : 76154
V42 : 76154
V43 : 76154
V44 : 76154
V45 : 76154
V46 : 76154
V47 : 76154
V48 : 76154
V49 : 76154
V50 : 76154
V51 : 76154
V52 : 76154
V53 : 75628
V54 : 75628
V55 : 75628
V56 : 75628
V57 : 75628
V58 : 75628
V59 : 75628
V60 : 75628
V61 : 75628
V62 : 75628
V63 : 75628
V64 : 75628
V65 : 75628
V66 : 75628
V67 : 75628
V68 : 75628
V69 : 75628
V70 : 75628
V71 : 75628
V72 : 75628
V73 : 75628
V74 : 75628
V75 : 72836
V76 : 72836
V77 : 72836
V78 : 72836
V79 : 72836
V80 : 72836
V81 : 72836
V82 : 72836
V83 : 72836
V84 : 72836
V85 : 72836
V86 : 72836
V87 : 72836
V88 : 72836
V89 : 72836
V90 : 72836
V91 : 72836
V92 : 72836
V93 : 72836
V94 : 72836
V138 : 406
V139 : 406
V140 : 406
V141 : 406
V142 : 406
V143 : 400
V144 : 400
V145 : 400
V146 : 406
V147 : 406
V148 : 406
V149 : 406
V150 : 400
V151 : 400
V152 : 400
V153 : 406
V154 : 406
V155 : 406
V156 : 406
V157 : 406
V158 : 406
V159 : 400
V160 : 400
V161 : 406
V162 : 406
V163 : 406
V164 : 400
V165 : 400
V166 : 400
V167 : 2389
V168 : 2389
V169 : 2417
V170 : 2417
V171 : 2417
V172 : 2389
V173 : 2389
V174 : 2417
V175 : 2417
V176 : 2389
V177 : 2389
V178 : 2389
V179 : 2389
V180 : 2417
V181 : 2389
V182 : 2389
V183 : 2389
V184 : 2417
V185 : 2417
V186 : 2389
V187 : 2389
V188 : 2417
V189 : 2417
V190 : 2389
V191 : 2389
V192 : 2389
V193 : 2389
V194 : 2417
V195 : 2417
V196 : 2389
V197 : 2417
V198 : 2417
V199 : 2389
V200 : 2417
V201 : 2417
V202 : 2389
V203 : 2389
V204 : 2389
V205 : 2389
V206 : 2389
V207 : 2389
V208 : 2417
V209 : 2417
V210 : 2417
V211 : 2389
V212 : 2389
V213 : 2389
V214 : 2389
V215 : 2389
V216 : 2389
V217 : 3957
V218 : 3957
V219 : 3957
V220 : 95
V221 : 95
V222 : 95
V223 : 3957
V224 : 3957
V225 : 3957
V226 : 3957
V227 : 95
V228 : 3957
V229 : 3957
V230 : 3957
V231 : 3957
V232 : 3957
V233 : 3957
V234 : 95
V235 : 3957
V236 : 3957
V237 : 3957
V238 : 95
V239 : 95
V240 : 3957
V241 : 3957
V242 : 3957
V243 : 3957
V244 : 3957
V245 : 95
V246 : 3957
V247 : 3957
V248 : 3957
V249 : 3957
V250 : 95
V251 : 95
V252 : 3957
V253 : 3957
V254 : 3957
V255 : 95
V256 : 95
V257 : 3957
V258 : 3957
V259 : 95
V260 : 3957
V261 : 3957
V262 : 3957
V263 : 3957
V264 : 3957
V265 : 3957
V266 : 3957
V267 : 3957
V268 : 3957
V269 : 3957
V270 : 95
V271 : 95
V272 : 95
V273 : 3957
V274 : 3957
V275 : 3957
V276 : 3957
V277 : 3957
V278 : 3957
V281 : 41
V282 : 41
V283 : 41
V288 : 41
V289 : 41
V296 : 41
V300 : 41
V301 : 41
V313 : 41
V314 : 41
V315 : 41

In [13]:
cols_to_drop = [col for col in small_df.columns if small_df[col].isna().sum() > 15000]
df_small = small_df.drop(columns=cols_to_drop)
df_small.shape

(82351, 275)

In [14]:
for i in df_small.columns:
    print(i, df_small[i].isna().sum())

TransactionID 0
isFraud 0
TransactionDT 0
TransactionAmt 0
ProductCD 0
card1 0
card2 397
card3 1
card4 11
card5 583
card6 7
addr1 343
addr2 343
P_emaildomain 11674
R_emaildomain 11426
C1 0
C2 0
C3 0
C4 0
C5 0
C6 0
C7 0
C8 0
C9 0
C10 0
C11 0
C12 0
C13 0
C14 0
D1 41
V95 0
V96 0
V97 0
V98 0
V99 0
V100 0
V101 0
V102 0
V103 0
V104 0
V105 0
V106 0
V107 0
V108 0
V109 0
V110 0
V111 0
V112 0
V113 0
V114 0
V115 0
V116 0
V117 0
V118 0
V119 0
V120 0
V121 0
V122 0
V123 0
V124 0
V125 0
V126 0
V127 0
V128 0
V129 0
V130 0
V131 0
V132 0
V133 0
V134 0
V135 0
V136 0
V137 0
V138 406
V139 406
V140 406
V141 406
V142 406
V143 400
V144 400
V145 400
V146 406
V147 406
V148 406
V149 406
V150 400
V151 400
V152 400
V153 406
V154 406
V155 406
V156 406
V157 406
V158 406
V159 400
V160 400
V161 406
V162 406
V163 406
V164 400
V165 400
V166 400
V167 2389
V168 2389
V169 2417
V170 2417
V171 2417
V172 2389
V173 2389
V174 2417
V175 2417
V176 2389
V177 2389
V178 2389
V179 2389
V180 2417
V181 2389
V182 2389
V183 2389
V184 2417
V185 2417
V186 2389
V187 2389
V188 2417
V189 2417
V190 2389
V191 2389
V192 2389
V193 2389
V194 2417
V195 2417
V196 2389
V197 2417
V198 2417
V199 2389
V200 2417
V201 2417
V202 2389
V203 2389
V204 2389
V205 2389
V206 2389
V207 2389
V208 2417
V209 2417
V210 2417
V211 2389
V212 2389
V213 2389
V214 2389
V215 2389
V216 2389
V217 3957
V218 3957
V219 3957
V220 95
V221 95
V222 95
V223 3957
V224 3957
V225 3957
V226 3957
V227 95
V228 3957
V229 3957
V230 3957
V231 3957
V232 3957
V233 3957
V234 95
V235 3957
V236 3957
V237 3957
V238 95
V239 95
V240 3957
V241 3957
V242 3957
V243 3957
V244 3957
V245 95
V246 3957
V247 3957
V248 3957
V249 3957
V250 95
V251 95
V252 3957
V253 3957
V254 3957
V255 95
V256 95
V257 3957
V258 3957
V259 95
V260 3957
V261 3957
V262 3957
V263 3957
V264 3957
V265 3957
V266 3957
V267 3957
V268 3957
V269 3957
V270 95
V271 95
V272 95
V273 3957
V274 3957
V275 3957
V276 3957
V277 3957
V278 3957
V279 0
V280 0
V281 41
V282 41
V283 41
V284 0
V285 0
V286 0
V287 0
V288 41
V289 41
V290 0
V291 0
V292 0
V293 0
V294 0
V295 0
V296 41
V297 0
V298 0
V299 0
V300 41
V301 41
V302 0
V303 0
V304 0
V305 0
V306 0
V307 0
V308 0
V309 0
V310 0
V311 0
V312 0
V313 41
V314 41
V315 41
V316 0
V317 0
V318 0
V319 0
V320 0
V321 0
V322 0
V323 0
V324 0
V325 0
V326 0
V327 0
V328 0
V329 0
V330 0
V331 0
V332 0
V333 0
V334 0
V335 0
V336 0
V337 0
V338 0
V339 0

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import KNNImputer

In [16]:
train_identity.shape

(144233, 41)

In [17]:
train_df.shape

(144233, 434)

In [18]:
train_identity.head()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [19]:
train_df.shape

(144233, 434)

In [20]:
train_df.describe()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,V330,V331,V332,V333,V334,V335,V336,V337,V338,V339
count,1.442330e+05,144233.000000,140872.000000,66324.000000,66324.000000,136865.000000,136865.000000,5155.000000,5155.000000,74926.000000,...,82041.000000,82041.000000,82041.000000,82041.000000,82041.000000,82041.000000,82041.000000,82041.000000,82041.000000,82041.000000
mean,3.236329e+06,-10.170502,174716.584708,0.060189,-0.058938,1.615585,-6.698710,13.285354,-38.600388,0.091023,...,0.777733,723.339755,1379.108414,1017.190218,9.837929,59.213495,28.592672,55.461163,151.546395,100.950114
std,1.788496e+05,14.347949,159651.816856,0.598231,0.701015,5.249856,16.491104,11.384207,26.084899,0.983842,...,4.735065,6222.466950,11181.344838,7964.623789,244.320100,388.035252,275.048519,669.707372,1096.739466,816.354359
min,2.987004e+06,-100.000000,1.000000,-13.000000,-28.000000,-72.000000,-100.000000,-46.000000,-100.000000,-36.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.077142e+06,-10.000000,67992.000000,0.000000,0.000000,0.000000,-6.000000,5.000000,-48.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.198818e+06,-5.000000,125800.500000,0.000000,0.000000,0.000000,0.000000,14.000000,-34.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.392923e+06,-5.000000,228749.000000,0.000000,0.000000,1.000000,0.000000,22.000000,-23.000000,0.000000,...,0.000000,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,3.577534e+06,0.000000,999595.000000,10.000000,0.000000,52.000000,0.000000,61.000000,0.000000,25.000000,...,55.000000,160000.000000,160000.000000,160000.000000,55125.000000,55125.000000,55125.000000,104060.000000,104060.000000,104060.000000

In [21]:
train_df.isna().sum()

TransactionID        0
id_01                0
id_02             3361
id_03            77909
id_04            77909
                 ...
V335             62192
V336             62192
V337             62192
V338             62192
V339             62192
Length: 434, dtype: int64